# Generated by Django 2.2 on 2020-10-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
